(() => {
  const practices = [
    ['tech','Tech Law'],['ai','AI Law'],['tax','Tax Law'],['real-estate','Real Estate'],['disputes','Disputes'],['ip','IP Law'],['employment','Employment Law'],['insurance','Insurance'],['energy','Energy Law']
  ];
  const practiceLinks = practices.map(([slug,name]) => `<a href="practice-detail.html?practice=${slug}">${name}</a>`).join('');
  const headerTarget = document.querySelector('[data-site-header]');
  if (headerTarget) headerTarget.outerHTML = `
    <header class="site-header inner-header"><div class="container nav-shell">
      <a class="brand" href="index.html" aria-label="Diamond Advocates home"><img src="images/Untitled-design-23.png" alt="Diamond Advocates"></a>
      <nav class="desktop-nav" aria-label="Primary navigation"><a class="nav-link" data-page="index.html" href="index.html">Home</a><div class="nav-item"><button class="nav-trigger" aria-expanded="false" aria-controls="practice-menu">Our Practice <span aria-hidden="true">⌄</span></button><div class="dropdown" id="practice-menu"><div class="dropdown-grid">${practiceLinks}</div></div></div><a class="nav-link" data-page="team.html,team-profile.html" href="team.html">Our Team</a><a class="nav-link" data-page="insights.html,article.html" href="insights.html">Insights</a><a class="nav-link" href="index.html#about">About</a><a class="nav-link" data-page="contact.html" href="contact.html">Contact</a></nav>
      <a class="btn btn--gold header-cta" href="contact.html">Book appointment <span>↗</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="mobile-menu" aria-label="Open menu"><span></span></button>
    </div></header><nav class="mobile-menu" id="mobile-menu" aria-label="Mobile navigation"><a href="index.html">Home</a><a href="practice-areas.html">Our Practice</a><div class="mobile-sub">${practiceLinks}</div><a href="team.html">Our Team</a><a href="insights.html">Insights</a><a href="contact.html">Contact & Appointment</a></nav>`;
  const footerTarget = document.querySelector('[data-site-footer]');
  if (footerTarget) footerTarget.outerHTML = `
    <footer class="site-footer"><div class="container"><div class="footer-grid"><div><img class="footer-brand" src="images/Untitled-design-23.png" alt="Diamond Advocates"><p>Guided by global vision and grounded in strong legal foundations, we create the solutions of tomorrow, today.</p><img class="partner-logo" src="images/Untitled-design-1024x386.png" alt="Diamond Advocates, partner of WONE Global"></div><div><h2 class="footer-title">Explore</h2><ul class="footer-links"><li><a href="practice-areas.html">Our Practice</a></li><li><a href="team.html">Our Team</a></li><li><a href="insights.html">Insights</a></li><li><a href="contact.html">Contact</a></li></ul></div><div><h2 class="footer-title">Practices</h2><ul class="footer-links"><li><a href="practice-detail.html?practice=tech">Tech Law</a></li><li><a href="practice-detail.html?practice=ai">AI Law</a></li><li><a href="practice-detail.html?practice=tax">Tax Law</a></li><li><a href="practice-areas.html">View all</a></li></ul></div><div><h2 class="footer-title">Contact</h2><ul class="footer-links"><li><a href="tel:+256414671838">0414 671 838</a></li><li><a href="mailto:info@diamondadvocates.com">info@diamondadvocates.com</a></li><li>Plot 1 Lourdel Road, 5th Floor Lourdel Towers, Nakasero, Kampala City</li></ul></div></div><div class="footer-bottom"><span>© 2026 Diamond Advocates. All rights reserved.</span><span>Privacy Policy · Legal Disclaimer (pages to be supplied)</span></div></div></footer><button class="back-to-top" aria-label="Back to top">↑</button>`;
})();
